name: CI/CD

on:
  push:
    branches:
      - main
      - develop
  pull_request:

env:
  SERVICE: lambda-requests-s3
  INFRA_DIR: infrastructure/aws
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  TERRAFORM_VERSION: 1.2.9

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sets env var for prod
        run: |
          echo "ENV=prd" >> $GITHUB_ENV
        if: github.ref == 'refs/heads/main'

      - name: Sets env var for stage or any other branch
        run: |
          echo "ENV=dev" >> $GITHUB_ENV
        if: github.ref != 'refs/heads/main'

      - name: Detect Changes on files
        id: changes
        uses: dorny/paths-filter@v2
        with:
          base: ${{ github.ref }}
          filters: |
            api:
              - 'src/**'
            infrastructure:
              - 'infrastructure/aws/common/**'
              - 'infrastructure/aws/${{ env.ENV }}/**'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${TERRAFORM_VERSION}

      - name: Package zip to upload
        id: package
        run: make package
        continue-on-error: true

      - name: Terraform Plan when it's a pull request and something has changed into the infra folder
        id: plan
        if: github.event_name == 'pull_request' && steps.changes.outputs.infrastructure == 'true'
        run: |
          terraform init
          PLAN_RESULT=$(terraform plan -no-color)
          if [ $? -eq 2 ]; then
            echo "$PLAN_RESULT"
            exit 1
          else
            echo "No changes detected in the plan."
          fi
        working-directory: ./${{ env.INFRA_DIR }}/${{ env.ENV }}
        continue-on-error: true

      - name: Update Pull Request with Plan if there is any change in infrastructure
        uses: actions/github-script@v5
        if: github.event_name == 'pull_request' && steps.changes.outputs.infrastructure == 'true'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const prAuthor = context.payload.pull_request.user.login;
            const event = github.context.eventName;
            const environment = process.env.ENV;
            const infraDir = process.env.INFRA_DIR;
            const planResult = `
                Environment: ${environment}
                Directory: ${infraDir}

                Terraform Plan:
                ${PLAN_RESULT}

                📖 (Pushed by: @${prAuthor}, Event: ${event})
                `;

            github.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: planResult
            });

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure' && steps.changes.outputs.infrastructure == 'true'
        run: exit 1

      - name: Terraform Apply if there is any change in infrastructure or in the code
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')  && github.event_name == 'push' && (steps.changes.outputs.infrastructure == 'true'  ||  steps.changes.outputs.api == 'true')
        run: |
          terraform init
          terraform apply --auto-approve
        working-directory: ./${{ env.INFRA_DIR }}/${{ env.ENV }}
